version: 2.1

executors:
  my-executor:
    working_directory: /tmp

jobs:
  build-job:
    executor: my-executor
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.1
    # circleci branch only master
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - run: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_artifacts:
          path: dist
          prefix: dist

            # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - echo-output    

  deploy-job:
    executor: my-executor
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    steps:
      - checkout
      - setup_remote_docker
       - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker build
          command: docker build -t excamad:latest .
      - run:
          name: docker push
          command: docker push deniskotov/excamad:latest

workflows:
  version: 2
  build_and_docker:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
