version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:8.9.1
    working_directory: /app

jobs:
  build-job:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - run: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_artifacts:
          path: dist
          prefix: dist

      - persist_to_workspace:
          root: workspace
          paths:
            - app

  deploy-job:
    executor: my-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /app/workspace
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker build
          command: docker build -t excamad:latest .
      - run:
          name: docker push
          command: docker push deniskotov/excamad:latest

workflows:
  version: 2
  build_and_docker:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
