version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.1
    # circleci branch only master
    branches:
      only:
        - master
        - /rc-.*/
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - run: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_artifacts:
          path: dist
          prefix: dist
#  deploy-job:
#    docker:
#     - image: circleci/openjdk:11.0.1-jdk
#    steps:
#      -
#
#workflows:
#  version: 2
#
#  -deploy:
#   jobs:
#     - build-job
#      - deploy-job:
#          requires:
#           - build-job
#         filters:
#            branches:
#              only: master
