version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/app/
    steps:
      - checkout
      - attach_workspace:
          at: ~/app/
      - restore_cache:
          key: v1-yarn-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
         key: v1-yarn-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: dist